<?php

use Illuminate\Database\Seeder;
use App\Menu;

class MenuTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

    	Menu::truncate();
    	$menus = array(
			array( // row #0
				'id' => 1,
				'menu_en' => 'Data Master',
				'menu_id' => 'Master Data',
				'parentid' => NULL,
				'class' => 'fa fa-bars',
				'url' => 'master',
				'user_group' => '1',
				'order_number' => 2,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-10 08:05:29',
				'updated_at' => '2017-05-10 08:05:29',
			),
			array( // row #1
				'id' => 2,
				'menu_en' => 'System Master',
				'menu_id' => 'Master Sistem',
				'parentid' => 1,
				'class' => NULL,
				'url' => 'master/system',
				'user_group' => '1',
				'order_number' => 3,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-10 08:05:29',
				'updated_at' => '2017-05-10 08:05:29',
			),
			array( // row #2
				'id' => 3,
				'menu_en' => 'Process Master',
				'menu_id' => 'Master Proses',
				'parentid' => 1,
				'class' => NULL,
				'url' => 'master/process',
				'user_group' => '1',
				'order_number' => 4,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-10 08:05:29',
				'updated_at' => '2017-05-10 08:05:29',
			),
			array( // row #3
				'id' => 4,
				'menu_en' => 'Employee Master',
				'menu_id' => 'Master Pegawai',
				'parentid' => 1,
				'class' => NULL,
				'url' => 'master/employee',
				'user_group' => '1',
				'order_number' => 5,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-10 08:05:29',
				'updated_at' => '2017-05-10 08:05:29',
			),
			array( // row #4
				'id' => 5,
				'menu_en' => 'Department Master',
				'menu_id' => 'Master Departemen',
				'parentid' => 1,
				'class' => NULL,
				'url' => 'master/department',
				'user_group' => '1',
				'order_number' => 6,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-10 08:05:29',
				'updated_at' => '2017-05-10 08:05:29',
			),
			array( // row #5
				'id' => 12,
				'menu_en' => 'Dashboard',
				'menu_id' => 'Dashboard',
				'parentid' => NULL,
				'class' => 'fa fa-tachometer',
				'url' => '',
				'user_group' => '1',
				'order_number' => 1,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-10 08:05:29',
				'updated_at' => '2017-05-10 08:05:29',
			),
			array( // row #6
				'id' => 14,
				'menu_en' => 'Position',
				'menu_id' => 'Jabatan',
				'parentid' => 1,
				'class' => NULL,
				'url' => 'master/position',
				'user_group' => '1',
				'order_number' => 14,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-10 08:05:29',
				'updated_at' => '2017-05-10 08:05:29',
			),
			array( // row #7
				'id' => 15,
				'menu_en' => 'Approval',
				'menu_id' => 'Penyetuju',
				'parentid' => 1,
				'class' => NULL,
				'url' => 'master/approval',
				'user_group' => '1',
				'order_number' => 15,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-10 08:05:29',
				'updated_at' => '2017-05-10 08:05:29',
			),
			array( // row #8
				'id' => 16,
				'menu_en' => 'Procedure',
				'menu_id' => 'Prosedur',
				'parentid' => NULL,
				'class' => 'fa fa-folder',
				'url' => 'procedure',
				'user_group' => '1',
				'order_number' => 3,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-10 08:05:29',
				'updated_at' => '2017-05-10 08:05:29',
			),
			array( // row #9
				'id' => 17,
				'menu_en' => 'Document',
				'menu_id' => 'Document',
				'parentid' => 1,
				'class' => '',
				'url' => 'master/document',
				'user_group' => '1',
				'order_number' => 5,
				'created_by' => NULL,
				'updated_by' => NULL,
				'created_at' => '2017-05-10 13:32:44',
				'updated_at' => '2017-05-10 13:32:44',
			),
			array( // row #10
				'id' => 18,
				'menu_en' => 'Settings',
				'menu_id' => 'Pengaturan',
				'parentid' => NULL,
				'class' => 'fa fa-cog',
				'url' => 'setting',
				'user_group' => '1',
				'order_number' => 99,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-16 10:06:05',
				'updated_at' => '2017-05-16 10:06:05',
			),
			array( // row #11
				'id' => 19,
				'menu_en' => 'Menu',
				'menu_id' => 'Menu',
				'parentid' => 18,
				'class' => NULL,
				'url' => 'setting/menu',
				'user_group' => '1',
				'order_number' => 1,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-16 10:06:42',
				'updated_at' => '2017-05-16 10:06:43',
			),
			array( // row #12
				'id' => 20,
				'menu_en' => 'User',
				'menu_id' => 'Pengguna',
				'parentid' => 18,
				'class' => NULL,
				'url' => 'setting/user',
				'user_group' => '1',
				'order_number' => 2,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-16 10:07:14',
				'updated_at' => '2017-05-16 10:07:14',
			),
			array( // row #13
				'id' => 21,
				'menu_en' => 'User Role',
				'menu_id' => 'Peran Pengguna',
				'parentid' => 18,
				'class' => NULL,
				'url' => 'setting/role',
				'user_group' => '1',
				'order_number' => 3,
				'created_by' => 'system',
				'updated_by' => NULL,
				'created_at' => '2017-05-16 10:10:37',
				'updated_at' => '2017-05-16 10:10:37',
			),
			array( // row #14
				'id' => 22,
				'menu_en' => 'APQP',
				'menu_id' => 'APQP',
				'parentid' => NULL,
				'class' => 'fa fa-folder-o',
				'url' => 'apqp',
				'user_group' => '1;2',
				'order_number' => 9,
				'created_by' => NULL,
				'updated_by' => NULL,
				'created_at' => '2017-06-06 07:41:35',
				'updated_at' => '2017-06-07 13:45:33',
			),
			array( // row #15
				'id' => 23,
				'menu_en' => 'Template',
				'menu_id' => 'Template',
				'parentid' => 18,
				'class' => '',
				'url' => 'setting/template',
				'user_group' => '1',
				'order_number' => 3,
				'created_by' => NULL,
				'updated_by' => NULL,
				'created_at' => '2017-06-07 13:00:28',
				'updated_at' => '2017-06-07 13:00:28',
			),
			array( // row #15
				'id' => 24,
				'menu_en' => 'Fill Record',
				'menu_id' => 'Isi Rekaman',
				'parentid' => NULL,
				'class' => 'fa fa-file',
				'url' => 'checksheet',
				'user_group' => '1;2',
				'order_number' => 10,
				'created_by' => NULL,
				'updated_by' => NULL,
				'created_at' => '2017-06-07 13:00:28',
				'updated_at' => '2017-06-07 13:00:28',
			),
			array(
				'id' => 25,
				'menu_en' => 'Revision',
				'menu_id' => 'Revisi',
				'parentid' => NULL,
				'class' => 'fa fa-pencil',
				'url' => 'revision',
				'user_group' => '1;2',
				'order_number' => 10,
				'created_by' => NULL,
				'updated_by' => NULL,
				'created_at' => '2017-06-07 13:00:28',
				'updated_at' => '2017-06-07 13:00:28',
			)
		);

		Menu::insert($menus);
    }
}